# Generated by Django 5.1 on 2024-08-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerInfo',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=30)),
            ],
            options={
                'db_table': 'InfluencerInfo',
            },
        ),
        migrations.CreateModel(
            name='SponsorInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'SponsorInfo',
            },
        ),
    ]
