# Generated by Django 4.2.11 on 2024-08-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='sponsorinfo',
            name='first_name',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='sponsorinfo',
            name='last_name',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.AlterField(
            model_name='influencerinfo',
            name='first_name',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='influencerinfo',
            name='last_name',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.AlterField(
            model_name='sponsorinfo',
            name='username',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
