# Generated by Django 4.2.11 on 2024-09-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_remove_sponsorinfo_id_sponsorinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerinfo',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
